export enum EInputEventType{
    MOUSEEVENT = 'MOUSEEVENT',
    MOUSEDOWN = 'MOUSEDOWN',
    MOUNSEUP = 'MOUNSEUP',
    MOUNSEMOVE = 'MOUNSEMOVE',
    MOUSEDRAG = 'MOUSEDRAG',
    KEYBOARDEVENT = 'KEYBOARDEVENT',
    KEYUP = 'KEYUP',
    KEYDOWN = 'KEYDOWN',
    KEYPRESS = 'KEYPRESS'
}